version: "3.9"

services:
  backend:
    image: node:18
    container_name: nodejs_backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3001:3000"
    command: ["npm", "run", "dev"]
    restart: unless-stopped

networks:
  timer-network:
    external: true  # Du musst dieses Netzwerk vorher erstellt haben!
