version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nodejs_backend
    ports:
      - "3001:3000"
    restart: unless-stopped
