services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: timer_backend
    ports:
      - "3001:3000"
    environment:
    restart: unless-stopped
