version: '3.8'

services:
  api:
    container_name: nodejs_backend
    image: node:20
    working_dir: /app
    # volumes:
    #  - .:/app
    command: CMD sh -c "ls -la src"

    ports:
      - "3100:3000"
   
